### ISSUE TITLE
Program Closes Unexpectedly

### ISSUE THREAD

**Issue by MakisChristou** [Equim-chan/vanity-monero#1]
My problem is when I use this combination of options: Standard mode, Monero main network, English, Match mode = 1. Even when I enter a valid prefix that is 1 character long, the program closes. If I put a prefix that needs more time to compute, the program tries for some amount of time and then closes instantly. Tried this on all the core options.

**Comment by Equim-chan** [comment]
Which OS are you using?

If a prefix has a lower difficulty, it will take shorter time to compute. When the computation is over, the result will be printed on the console. I think the problem here is that Windows (assuming you are using it) shutdown the console immediately after the result is printed.

This shouldn't happen since I already added a blocker for Windows at https://github.com/Equim-chan/vanity-monero/blob/b8e2c294e5c644689a91406de11f3eb5c87606c5/cmd/vanity-monero/main.go#L619-L622, which halt the program and waits until an Enter key input is triggered to exit. So I think it may be some other kind of problem.

A temporary solution is to run `cmd.exe`, use `cd` to change directory to the program's path, then run it there. This way, even if the program exits somehow instantly, the window won't disappear. Also, please paste the output here if there is any error spotted. Thanks.

**Comment by fedpettinella** [comment]
@MakisChristou you may be running the incorrect binary. If your CPU is 64-bit, make sure to choose the binary for your OS ending in `amd64`. If it's 32-bit, use the binary ending in 386. Another person on Reddit had a similar probelm to yours and I suggested the same fix to them. [[reddit link](https://www.reddit.com/r/Monero/comments/8o8wdz/i_just_wrote_a_vanity_address_generator_for_monero/e2i0bkm/?context=3)]

**Comment by MakisChristou** [comment]
I was using the wrong binary thanks !!!
